version: "3.8"

services:
  accounts:
    image: thaisc98/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - thaisc98-network

  loans:
    image: thaisc98/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - thaisc98-network

  cards:
    image: thaisc98/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - thaisc98-network

networks:
  thaisc98-network: