version: "3.8"

services:

  configserver:
    image: thaisc98/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - thaisc98-network

  accounts:
    image: thaisc98/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - thaisc98-network
    depends_on:
      - configserver
    deploy:
       restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 3
            window: 120s
    environment:
        SPRING_PROFILES_ACTIVE: dev
        SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  loans:
    image: thaisc98/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - thaisc98-network
    depends_on:
      - configserver
    deploy:
       restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 3
            window: 120s
    environment:
        SPRING_PROFILES_ACTIVE: dev
        SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
    

  cards:
    image: thaisc98/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - thaisc98-network
    depends_on:
      - configserver
    deploy:
       restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 3
            window: 120s
    environment:
        SPRING_PROFILES_ACTIVE: dev
        SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

networks:
  thaisc98-network: